---
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: {{ .Values.autoscalerNamespace}}
data:
  .dockerconfigjson: {{ .Values.secrets.myregistrykey.dockerconfigjson | quote }}
type: kubernetes.io/dockerconfig.json